service: webwizardsserverless
frameworkVersion: '3'
configValidationMode: error

plugins:
  -serverless-webpack

package: 
    individually: true 

provider:
  name: aws
  runtime: nodejs20.x
  profile: David 
  region: eu-north-1
  iam: 
    role: arn:aws:iam::497017796861:role/service-role/web-wizards
    
# Här är våra lambdafunktioner
functions:
  lambdaGetMenu:
    handler: backend/LambdaGETMenu.handler
    events:
      - httpApi:
          path: /webwizards/menu
          method: GET

  lambdaGetidMenu:
    handler: backend/LambdaGETidMenu.handler
    events:
      - httpApi:
          path: /webwizards/menu/{sk}
          method: GET

  lambdaPUTMenu:
    handler: backend/LambdaPUTMenu.handler
    events:
      - httpApi:
          path: /webwizards/menu/{sk}
          method: PUT

  lambdaGetUsers:
    handler: backend/LambdaGETUsers.handler
    events:
      - httpApi:
          path: /webwizards/users
          method: GET

  lambdaGetidUsers:
    handler: backend/LambdaGETidUsers.handler
    events:
      - httpApi:
          path: /webwizards/users/{id}
          method: GET

  lambdaGetOrders:
    handler: backend/LambdaGETOrders.handler
    events:
      - httpApi:
          path: /webwizards/orders
          method: GET

  lambdaPostOrders:
    handler: backend/LambdaPOSTOrders.handler
    events:
      - httpApi:
          path: /webwizards/orders
          method: PUT

  lambdaGetIdOrders:
    handler: backend/LambdaGETidOrders.handler
    events:
      - httpApi:
          path: /webwizards/orders/{ordersId}
          method: GET

  lambdaPutOrders:
    handler: backend/LambdaPUTOrders.handler
    events:
      - httpApi:
          path: /webwizards/orders/{ordersId}
          method: PUT

  lambdaDeleteOrders:
    handler: backend/LambdaDELETEOrders.handler
    events:
      - httpApi:
          path: /webwizards/orders/{ordersId}
          method: DELETE

resources:      
  Resources:
  # Menu Table
    MenuTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: MenuTable
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: "S"
          - AttributeName: "sk"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: "pk"
            KeyType: HASH
          - AttributeName: "sk"
            KeyType: RANGE

    # Order Table
    orderTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: orderTable
        AttributeDefinitions:
          - AttributeName: "pk"
            AttributeType: "S"
          - AttributeName: "ordersId"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: false
        KeySchema:
          - AttributeName: "pk"
            KeyType: HASH
          - AttributeName: "ordersId"
            KeyType: RANGE
        # GlobalSecondaryIndexes:
        #   - IndexName: ordersIndex
        #     KeySchema:
        #       - AttributeName: "ordersId"
        #         KeyType: HASH
        #     Projection:
        #       ProjectionType: "ALL"

#     WebWizardsBucketBackend:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: web-wizards-bucket-backend
    
#     WebWizardsBucketWebpage:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: web-wizards-bucket-webpage
